/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuoteId = IDL.Nat;
export const ServiceType = IDL.Variant({
  'lineStriping' : IDL.Null,
  'sealcoating' : IDL.Null,
  'parkingLotPaving' : IDL.Null,
  'asphaltRepair' : IDL.Null,
  'drivewayPaving' : IDL.Null,
});
export const QuoteRequest = IDL.Record({
  'id' : QuoteId,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'submitQuoteRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuoteId = IDL.Nat;
  const ServiceType = IDL.Variant({
    'lineStriping' : IDL.Null,
    'sealcoating' : IDL.Null,
    'parkingLotPaving' : IDL.Null,
    'asphaltRepair' : IDL.Null,
    'drivewayPaving' : IDL.Null,
  });
  const QuoteRequest = IDL.Record({
    'id' : QuoteId,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'submitQuoteRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };